### ISSUE TITLE
ie9 报错

### ISSUE THREAD

**Issue by NexusLee** [RubyLouvre/mmRouter#103]
SCRIPT438: 对象不支持“apply”属性或方法 
mmRouter.js?_v=0.0.0, 行167 字符17

**Comment by RubyLouvre** [comment]
给例子，你这样我也不知道你用什么版本

**Comment by NexusLee** [comment]
![image](https://cloud.githubusercontent.com/assets/4703440/11799930/f2b2985c-a312-11e5-9e19-63ef29866d79.png)

@RubyLouvre  貌似是这个地方 avalon.mobile.shim.js 1.4.7.1 built in 2015.11.19

**Comment by NexusLee** [comment]
![qq 20151215100720](https://cloud.githubusercontent.com/assets/4703440/11800063/33433268-a314-11e5-9114-d0f601bc81dc.png)


@RubyLouvre 貌似是这个地方 avalon.mobile.shim.js 1.4.7.1 built in 2015.11.19 运行时出错

**Comment by RubyLouvre** [comment]
console.log是一个函数，肯定有apply方法
