### ISSUE TITLE
hasAttribute在低版本ie下报错

### ISSUE THREAD

**Issue by mho-calc** [RubyLouvre/mmRouter#119]
mmRouter.js的569行和mmHistory.js的264行
使用了hasAttribute，hasAttribute是dom l2里面的，ie6-8都是不支持的，可以换成用getAttribute()===null来判断
前几天也发现一个低版本ie的兼容bug，是不是最近不做低版本ie的适配工作了？

**Comment by RubyLouvre** [comment]
已经修正

**Comment by mho-calc** [comment]
这个问题的后面几行……之前我判断写反了没发现，还有一个兼容性问题，preventDefault全版本ie都不支持，ie下要用returnValue=false
