### ISSUE TITLE
请教关于mmState的一个问题

### ISSUE THREAD

**Issue by cxyguopong** [RubyLouvre/mmRouter#27]
我现在遇到一个问题 希望您能解答一下（用的是mmState）

我定义了一种状态，对应的模板里有一个UI组件库 loading，在地址处于该状态的时候，我让该模板的loading组件显示。第一次是成功的。

但是第二次又跳到该种状态的时候提示loading视图为undefined( avalon.vmodels['loadingName'] )。报错。开始我以为是模板未载入完的原因，所以将调用loading的代码放至了onAfterLoad里面，第一次加载模板后是没问题的 ，但第二次跳到该种状 依然有这个错误。

**Comment by gogoyqj** [comment]
元素被销毁了？把代码贴出来瞅瞅
