### ISSUE TITLE
absolute:true切换，this.params参数不会改变

### ISSUE THREAD

**Issue by ascoders** [RubyLouvre/mmRouter#39]
#37 修复后，absolute:true的父级可以获取到this.params了，但是只有第一次是准确的，以后刷新都会这个参数值都没变。子集获得的this.params是准确的。

**Comment by gogoyqj** [comment]
你这描述的啥。。。

**Comment by gogoyqj** [comment]
改成每次state切换都去覆盖父状态的params了

**Comment by ascoders** [comment]
赞
