### ISSUE TITLE
mmState 的 avalon.router.go() 方法 Bug

### ISSUE THREAD

**Issue by aidenzou** [RubyLouvre/mmRouter#40]
```javascript
avalon.state("ordersuccess", {
        controller: "page",
        url: "/order/success/{orderId}",
        views: {
            "": {
                templateUrl: "./modules/ordersuccess/tpl.html"
            },
            'title@': {
                template: "订单"
            }
        },
        onChange: function (orderId) {
            orderId || avalon.router.go("home");
            console.log('有被执行')
        }
    });
```

### 如上demo，avalon.router.go("home");  这里的 go() 方法存在如下问题：
- 不能阻止下面的语句继续执行，而是下面的语句可以继续执行；
- 视图跳转到相应的 'home'，但是 路由还处于当前状态，并不是 home 的路由状态

**Comment by gogoyqj** [comment]
这个go肯定没办法阻止后面的语句继续执行。。。

**Comment by gogoyqj** [comment]
视图跳转到相应的 'home'，但是 路由还处于当前状态，并不是 home 的路由状态 - 这个你是说，url状态不对？- 这个问题修了

**Comment by gogoyqj** [comment]
视图跳转到相应的 'home'，但是 路由还处于当前状态，并不是 home 的路由状态 - 这个问题已修

**Comment by aidenzou** [comment]
刚才更新了最新版之后(视图跳转到相应的 'home'，但是 路由还处于当前状态，并不是 home 的路由状态) 这个问题已解决，多谢

**Comment by aidenzou** [comment]
（不能阻止下面的语句继续执行，而是下面的语句可以继续执行） 那这个问题是不是就只能在业务代码里边这边处理了
