### ISSUE TITLE
requireJs 和 mmState内部使用的avalon.require冲突问题

### ISSUE THREAD

**Issue by waipy** [RubyLouvre/mmRouter#67]
当使用requireJs加载器的时候，禁用avalon内部的loader,而mmState默认使用的是 avalon的加载器，造成
mmState中的 controllerUrl后面的参数加载出现bug,这个怎么解决呀！

**Comment by gogoyqj** [comment]
avalon.controller.loader - 重写这个函数

**Comment by RubyLouvre** [comment]
```
avalon.require = requirejs
```
