### ISSUE TITLE
请问ignoreChange有哪些使用场景或者推荐的用法抑或最佳实践！

### ISSUE THREAD

**Issue by IndexXuan** [RubyLouvre/mmRouter#77]
看了mmRouter-demo-list里在列表页用了，还有源码文档里写了几句。还是有些疑问。请正妹老师说几句或者有使用心得的朋友总结一下。感觉这个属性应该对性能优化有帮助但是不应该滥用吧。

源码里写道：  更新视图时调用该函数，为true时不会去重写视图和scan，请确保该视图内用到的数据没有放到avalon vmodel $skipArray内。
列子里写道：  url通过{}配置的参数变量发生变化的时候是否通过innerHTML重刷ms-view，默认会，如果你做的是翻页应用，建议使用例子内的配置，把数据更新到vmodel上即可。

如果做类似做题的场景，题目经常切换且很多，而且题目类型不同会使用不同的模版，该使用这个属性吗？

**Comment by gogoyqj** [comment]
@IndexXuan ignoreChange是用来，做翻页这种东西【我的例子里应该很清楚的表现了这个意思】 - 设置为true就以为这，这块视图如果只是params活着query变化，那么就不通过innerHTML来更新，而是让avalon mvvm来更新dom

**Comment by IndexXuan** [comment]
@gogoyqj 嗯嗯，你表达的很清楚了。是啊，视图有可能是完全不同的就用http request请求来用innerHTML替换模板，而这种基本模板不变，数据变幻的，当然就是利用mvvm能力了。多谢！avalon还是得向正美老师，向你这样的多学习，好好利用，共同进步。多谢你的一些例子和demo，很受用。
