### ISSUE TITLE
viewCache、cacheController 禁用路由缓存无效

### ISSUE THREAD

**Issue by Quansen** [RubyLouvre/mmRouter#82]
需求：路由改变时需要保证<code>JS</code>每次都要执行。
配置了 viewCache、cacheController 为 false 还是生成 dom cache。

**Comment by gogoyqj** [comment]
@Quansen  你估计是用错了。。。看文档

viewCache优先级： ms-view元素上的data-view-cache 低于 view配置 viewCache

**Comment by IndexXuan** [comment]
@gogoyqj  请问这个viewCache我没设置，应该就是false吧。可是我的应用比如三层目录的那种文章应用（首页，列表页，详情页），详情页经常会进去是上次查看的文章，0.1秒后变成新文章，这闪眼的一下体验很不好，有什么改进方法吗。现在我的解决办法就是loading时间故意加长。。。而且看过的文章（就是渲染过的）文章，进去就是好的，不闪屏。好像自动做了cache，很神奇。。。我是不是文章页该用下ignoreChange，哈哈。

其实好像还是mmState并没有真正的rendered回调，现在只是scan之后，但是页面dom并不一定准备好了，就给用户呈现了。。。

**Comment by Quansen** [comment]
@gogoyqj 你好，我就是在view配置 viewCache，ms-view元素没有设置data-view-cache 。

**Comment by gogoyqj** [comment]
这个是require的缓存
