### ISSUE TITLE
avalon.router.get 回调两次

### ISSUE THREAD

**Issue by gaojianqi6** [RubyLouvre/mmRouter#84]
![image](https://cloud.githubusercontent.com/assets/1460571/9380000/d9fa0782-475f-11e5-9999-8fbd65c08cfa.png)

**Comment by gaojianqi6** [comment]
我在我的网页中试了一下，看到callback跳了一下， 看着不对 ，然后直接用的mmRouter的git里面带的例子调试发现每次都掉了两次callback。。

**Comment by gaojianqi6** [comment]
可以直接 加我QQ 0.0 ➡️  569036120 ，泡完妹子赶紧来帮我啊 ～》～

**Comment by gaojianqi6** [comment]
可以直接 加我QQ 0.0 ➡️ 568936120 ，泡完妹子赶紧来帮我啊 ～》～

**Comment by gogoyqj** [comment]
@gaojianqi6  这里的代码太老了。。。你先从 oniui那里更新吧，最新的代码是没有问题的

**Comment by gaojianqi6** [comment]
我直接 用这个了
http://ued.qunar.com/oniui/mmRouter/avalon.mmRouter.ex.html#!/tab1 
在下面加了一句
console.log("当前页是:" + page + ",lastPath:" + avalon.router.getLastPath());
依然是有问题
![image](https://cloud.githubusercontent.com/assets/1460571/9406267/831a2a50-4831-11e5-8a47-2709a7d6c7eb.png)
