### ISSUE TITLE
请问目前的mmState里面$ctrl的$onRendered回调是不是只是scan完成，但是不保证全部页面dom结构建立完毕，符合预期？

### ISSUE THREAD

**Issue by IndexXuan** [RubyLouvre/mmRouter#87]
不知是我自己没学好还是真的只是写的那样，只是scan完毕就回调，可dom貌似并不一定建立完毕，给需要二次渲染的一些dom造成麻烦，现在都是用enough time的延时来做。（毕竟一些mvvm组件有时候还是不如过去的dom组件库好用，一些触屏轮播，滑动导航条组件目前项目里还是用的别的组件库，需要预期一些特定dom结构再渲染，以前是后端模板来的时候就是预期的dom，现在得先前端渲染，再二次渲染）。

希望能变成真正的页面渲染完成的回调，如其名。嘿嘿。不知道实现起来怎么样，感觉现在是不是框架下个命令去渲染一些东西，但是真正最后一个dom渲染完毕了并不好捕捉啊。总不能轮询来看看dom是否符合预期了啊。

可能有很多不对的地方，求指正，求赐教，谢谢大家！

**Comment by IndexXuan** [comment]
目前针对组件用局部的data-repeat-rendered等一些回调解决了，为了保险加了很小的延时。基本满足要求了

**Comment by gogoyqj** [comment]
只保证把ms-view内元素scan一遍，而有的绑定的scan是有异步的，比如repeat
