### ISSUE TITLE
mmState里面的_parseArgs函数在处理64位long值的时候会出问题

### ISSUE THREAD

**Issue by fanliao** [RubyLouvre/mmRouter#95]
具体在121行 val = JSON.parse(value) 这句代码这里。

如果url是这样的：club/307816941114885120
那么JSON.parse(“307816941114885120”)的结果会变成307816941114885100

**Comment by RubyLouvre** [comment]
这个没法处理，JSON.parse 是原生API，你不要传大数就行了

**Comment by fanliao** [comment]
问题是系统里面的id是64位的，能否检查结果不对，然后直接用value，我debug看到value是个字符串，不会变

**Comment by RubyLouvre** [comment]
让后端传过来时处理一下3078169-41114885120

**Comment by fanliao** [comment]
正美你提的也是个思路，不过我们的API还要给其他APP客户端使用，这样改变动较大。系统所有表的Id又都是64位的，用到的地方很多。
我现在是后端加个字符串类型的值传递过来，然后先直接在mmState里面改成val=value，因为我们的参数除了字符串和数字，不会有别的类型

**Comment by RubyLouvre** [comment]
传过来后，你再将-去掉;要不会遇到双精度问题
